# Generated by Django 4.0.6 on 2022-07-22 11:27
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kazan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField()),
                ('portions', models.IntegerField()),
                ('wall_thickness', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
