# Generated by Django 4.0.6 on 2022-08-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_kazan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='kazan',
            name='price_new',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
