# Generated by Django 4.0.6 on 2022-08-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_kazan_price_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kazan',
            options={'ordering': ['id'], 'verbose_name': 'Казаны', 'verbose_name_plural': 'Казаны'},
        ),
        migrations.AddField(
            model_name='kazan',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AddField(
            model_name='kazan',
            name='photo',
            field=models.ImageField(default=1, upload_to='photos/%Y/%m/%d', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kazan',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='kazan',
            name='price_new',
            field=models.IntegerField(verbose_name='Новая цена'),
        ),
        migrations.AlterField(
            model_name='kazan',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='kazan',
            name='volume',
            field=models.IntegerField(verbose_name='Объём'),
        ),
    ]
